scrape_configs:
  - job_name: 'Mercurius'
    metrics_path: '/metrics'
    scrape_interval: 1ms
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Mercurius'
